name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: extractions/setup-just@v1
      - name: Generate GitHub App token
        id: llm_cli_app
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Configure git credentials for private dependencies
        run: |
          git config --global url."https://x-access-token:${{ steps.llm_cli_app.outputs.token }}@github.com/".insteadOf https://github.com/
      - run: python -m pip install --upgrade pip
      - run: just install
      - run: just lint
      - run: just test
      - run: just build
