name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: extractions/setup-just@v1
      - name: Generate GitHub App token
        id: llm_cli_app
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Configure git credentials for private dependencies
        run: |
          git config --global url."https://x-access-token:${{ steps.llm_cli_app.outputs.token }}@github.com/".insteadOf https://github.com/
      - run: python -m pip install --upgrade pip
      - run: just install
      - run: just lint
      - name: Install test extras
        run: python -m pip install pytest pytest-cov coverage
      - name: Run pytest with coverage
        run: python -m pytest --cov=src --cov-report=xml --cov-report=term-missing
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 14
      - name: Prepare coverage comment
        if: github.event_name == 'pull_request'
        id: coverage_comment
        run: |
          python .github/scripts/post_coverage_comment.py \
            --coverage-file coverage.xml \
            --output-file .build/tmp/coverage_comment.md
          {
            echo 'comment<<EOF'
            cat .build/tmp/coverage_comment.md
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Post sticky coverage comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: coverage-report
          message: ${{ steps.coverage_comment.outputs.comment }}
          recreate: true
          hide_and_recreate: true
      - run: just build
