name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: extractions/setup-just@v1
      - run: python -m pip install --upgrade pip
      - run: just install
      - run: just lint
      - run: just test
      - run: just build
