name: docs-quality

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CLAUDE.md'
      - '.docs-templates/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Install project dependencies
        run: just install
      - name: Docs quality checks (markdownlint + cspell + lychee)
        run: just docs check
